name: xcrypto
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - pyarrow
  - rust>=1.74
  - maturin>=1.5
  - openssl
  - pkg-config
  - cmake
  - make
  - git
  - pip:
      - websockets
      - ipykernel

