name: cryptoflow
channels:
  - conda-forge
dependencies:
  # Python runtime
  - python=3.11
  - pip
  
  # System-level dependencies for Rust compilation
  - rust>=1.74
  - maturin>=1.5
  - openssl
  - pkg-config
  - cmake
  - make
  - git
  
  # All Python packages managed via requirements.txt
  - pip:
      - -r requirements.txt

